### ISSUE TITLE
Publish introduction thread request

### ISSUE THREAD

**Issue by poikcue** [SimplyRin/ProtocolChanger#1]
(Sorry to create this issue, because I can't contact you through Discord)
Can I post an introduction post on mcbbs (mcbbs.net)? I will not post jar files and link github and spotmc pages in the thread that allow to download it.
I will explain that the plugin is made by you and includes a MIT license.
Thanks!

**Comment by SimplyRin** [comment]
Sorry for my late reply.
You can post it on mcbbs.
Thank you.
